"""
generate_images.py — StoicElderWisdom
Generates 15 cinematic images. Warm, contemplative, unhurried.
Tries Gemini imagen first, falls back to Pollinations/Flux.
Reads from output/image_prompts.json if present (generated by generate_script.py).
"""
import base64
import json
import os
import time
import requests
from pathlib import Path

OUTPUT_DIR = Path("generated_images")
OUTPUT_DIR.mkdir(exist_ok=True)


def load_api_key() -> str:
    key = os.environ.get("GEMINI_API_KEY")
    if key:
        return key
    env = Path(".env")
    if env.exists():
        for line in env.read_text().splitlines():
            if line.startswith("GEMINI_API_KEY="):
                return line.split("=", 1)[1].strip()
    raise ValueError("GEMINI_API_KEY not found")


# Fallback prompts — warm, contemplative, StoicElderWisdom aesthetic
PROMPTS = [
    {"label": "01_older_man_window_golden", "prompt": "Cinematic 16:9. An older man, late 60s, sits alone at a large window. Evening golden light falls across his weathered hands resting on the sill. His expression is thoughtful, peaceful. Warm amber tones. Slightly desaturated. Slow, contemplative mood."},
    {"label": "02_still_autumn_lake", "prompt": "Cinematic 16:9. A perfectly still mountain lake at dawn, reflecting bare autumn trees and soft grey sky. Mist rises from the water. Warm, slightly desaturated palette. No people. Deep quiet. Unhurried."},
    {"label": "03_hands_holding_old_book", "prompt": "Cinematic 16:9. Close-up of weathered, aged hands holding an open, well-worn leather book. Candlelight from off-screen. Warm amber shadows. The hands show decades of life. Intimate, still."},
    {"label": "04_roman_bust_candlelight", "prompt": "Cinematic 16:9. Ancient Roman marble bust in soft candlelight. The bust faces slightly away. Warm amber light on one side, deep shadow on the other. Timeless. Dark background. Dignified."},
    {"label": "05_forest_path_autumn_dusk", "prompt": "Cinematic 16:9. A lone older man walks slowly down a quiet forest path covered in fallen leaves. Autumn. Late afternoon golden light filtering through bare trees. His back is to us. Unhurried pace. Warm, slightly desaturated."},
    {"label": "06_fireplace_embers_evening", "prompt": "Cinematic 16:9. Close-up of a stone fireplace with glowing embers and one low flame. Warm amber and orange. Dark room beyond. A leather armchair just visible at the edge. Quiet, intimate. Evening mood."},
    {"label": "07_ancient_stone_ruins_sunrise", "prompt": "Cinematic 16:9. Ancient Roman or Greek stone ruins at golden hour sunrise. Columns casting long warm shadows. Empty, silent landscape beyond. Warm golden light. Slightly desaturated. Timeless and still."},
    {"label": "08_older_man_sitting_fire", "prompt": "Cinematic 16:9. Older man sitting alone beside an outdoor fire at dusk. His face lit warmly from below. Mountains or dark trees in background. Contemplative expression. No phone, no distractions — just a man and the fire."},
    {"label": "09_library_shelves_candlelight", "prompt": "Cinematic 16:9. A dark, wood-paneled library lined with old books. A single candle burns on a reading desk. Warm amber light catches book spines. Deep shadows. No people. Like a room that holds centuries of thought."},
    {"label": "10_mountain_mist_morning", "prompt": "Cinematic 16:9. Rolling mountain ridges disappearing into morning mist. Layered blue-grey and warm gold tones. Still, expansive, unhurried. No people, no buildings. Just the ancient land."},
    {"label": "11_weathered_hands_table", "prompt": "Cinematic 16:9. Extreme close-up of two weathered hands resting flat on a worn wooden table. Afternoon light from a nearby window. Wedding ring just visible. Still, contemplative. The hands of a man who has worked and loved and lost."},
    {"label": "12_older_man_alone_bench_park", "prompt": "Cinematic 16:9. An older man sits alone on a park bench in autumn. Trees behind him in warm amber and gold. He looks into the distance. The bench beside him is empty. Gentle, melancholy warmth."},
    {"label": "13_open_journal_pen_morning", "prompt": "Cinematic 16:9. An open leather journal with handwritten pages, a fountain pen resting across it. Morning light from a window. A cup of coffee just out of focus beyond. Warm, quiet, intimate."},
    {"label": "14_sunset_over_hills_lone_tree", "prompt": "Cinematic 16:9. A single ancient oak tree silhouetted on a hilltop against a deep orange and gold sunset. Vast quiet landscape. Warm desaturated tones. Still and timeless."},
    {"label": "15_older_man_looking_mirror", "prompt": "Cinematic 16:9. An older man stands before a bathroom mirror in soft morning light. He looks at his own reflection thoughtfully. Not with vanity — with recognition. Warm, slightly desaturated. Intimate. The quiet moment before the day begins."},
]


def generate_image_gemini(label: str, prompt: str, api_key: str) -> bool:
    filepath = OUTPUT_DIR / f"{label}.jpg"
    url = (
        "https://generativelanguage.googleapis.com/v1beta/"
        f"models/gemini-2.5-flash-image:generateContent?key={api_key}"
    )
    payload = {
        "contents": [{"parts": [{"text": f"Generate an image: {prompt}"}]}],
        "generationConfig": {"responseModalities": ["IMAGE"]},
    }
    try:
        resp = requests.post(url, json=payload, timeout=120)
        if resp.status_code in (429, 400):
            return False
        resp.raise_for_status()
        parts = resp.json()["candidates"][0]["content"]["parts"]
        for part in parts:
            if "inlineData" in part:
                filepath.write_bytes(base64.b64decode(part["inlineData"]["data"]))
                return True
    except Exception:
        pass
    return False


def generate_image_pollinations(label: str, prompt: str) -> bool:
    import urllib.request, urllib.parse
    filepath = OUTPUT_DIR / f"{label}.jpg"
    encoded  = urllib.parse.quote(prompt[:500])   # cap length
    # Try free Pollinations models in order
    for model in ["turbo", "flux-schnell", "stable-diffusion-xl-base-1.0"]:
        url = (f"https://image.pollinations.ai/prompt/{encoded}"
               f"?width=1792&height=1024&model={model}&nologo=true")
        for attempt in range(1, 3):
            try:
                req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
                with urllib.request.urlopen(req, timeout=90) as r:
                    data = r.read()
                filepath.write_bytes(data)
                time.sleep(10)
                return True
            except Exception as e:
                err = str(e)
                if "402" in err:
                    print(f"    Pollinations/{model} requires payment - trying next model...")
                    break   # skip remaining attempts for this model
                print(f"    Pollinations/{model} attempt {attempt} failed: {e}")
                if attempt < 2:
                    time.sleep(20)
    return False


def generate_image_huggingface(label: str, prompt: str) -> bool:
    """Free fallback via Hugging Face Inference API — no key required for public models."""
    filepath = OUTPUT_DIR / f"{label}.jpg"
    url = "https://api-inference.huggingface.co/models/stabilityai/stable-diffusion-xl-base-1.0"
    for attempt in range(1, 4):
        try:
            resp = requests.post(url, json={"inputs": prompt[:300],
                                 "parameters": {"width": 1024, "height": 576}}, timeout=120)
            if resp.status_code == 503:
                print(f"    HuggingFace model loading, waiting 20s...")
                time.sleep(20)
                continue
            resp.raise_for_status()
            filepath.write_bytes(resp.content)
            return True
        except Exception as e:
            print(f"    HuggingFace attempt {attempt} failed: {e}")
            if attempt < 3:
                time.sleep(15)
    return False


def generate_image(label: str, prompt: str, api_key: str) -> None:
    filepath = OUTPUT_DIR / f"{label}.jpg"
    if filepath.exists():
        print(f"  Skipping (already exists): {filepath}")
        return
    print(f"Generating: {label}")
    if generate_image_gemini(label, prompt, api_key):
        print(f"  Saved (Gemini): {filepath}")
        time.sleep(3)
    elif generate_image_pollinations(label, prompt):
        print(f"  Saved (Pollinations fallback): {filepath}")
    elif generate_image_huggingface(label, prompt):
        print(f"  Saved (HuggingFace fallback): {filepath}")
    else:
        print(f"  WARNING: all image sources failed for {label} — pipeline will continue")


def main():
    api_key = load_api_key()

    prompts = PROMPTS
    prompts_file = Path("output/image_prompts.json")
    if prompts_file.exists():
        prompts = json.loads(prompts_file.read_text(encoding="utf-8"))
        print(f"Loaded {len(prompts)} image prompts from output/image_prompts.json")

    print(f"Generating {len(prompts)} images into '{OUTPUT_DIR}/'...\n")
    for item in prompts:
        generate_image(item["label"], item["prompt"], api_key)
    print("\nDone.")


if __name__ == "__main__":
    main()
